apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: mi-micro
spec:
  selector:
    matchLabels:
      app: mi-micro
  replicas: 1 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: mi-micro
    spec:
      containers:
      - name: mi-micro
        image: icatala198724/microservice-laravel-octane-swoole:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mi-micro
  labels:
    app: mi-micro
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: mi-micro